server:
  port: 8080

spring:
  application:
    name: institution-service

  datasource:
    url: jdbc:postgresql://localhost:5432/institucion_db
    username: postgres
    password: "simurdiera77"
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.athenet.institution: DEBUG